version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3332:80" 
    networks:
      - medilearn-network

  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"  
    networks:
      - medilearn-network

networks:
  medilearn-network:
    driver: bridge

