version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    networks:
      - medilearn-network

  backend:
    build: ./backend
    ports:
      - "3000:3000"
    networks:
      - medilearn-network

networks:
  medilearn-network:
    driver: bridge

